language: java
jdk: openjdk8
deploy:
  provider: releases
  api_key:
    secure: K4a7fP2Jn4+hf5NWci00EmPvycJbixbhiVIOoiO0NCZA26xt+zILEEV/uXCvuVnbpuEuFsgvftYI0u3oX2QoMC3XduWdhVlRko9d42UDkyt1ts5YisnN6/cGEjxKDIiHPmVvZfP+5uY5E/Ca/dPO3tM7kEP4vJG2O1NXEGsvi7c=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-gitlab-plugin
notifications:
  slack:
    secure: tAyBk+cR6aqqZ9aHgnpyGs0wViE3r1F6Oh1cQm58uSzunfems1SOodEWA1s8xdaVesRYa0VGAxlb/qVyWIyBQ2XHSrnFp1nwIIIL7f3v6V9/y7l3gpp2zi5BqZy9nT0UtX7wnefXCOVd/Ga2M343ux/Ad7NQlooq/gBdV/g1osw=
